service: photodrop-api-admin
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-export-env

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    HASHER_SALT: ${env:HASHER_SALT}
    JWT_SIGNING_KEY: ${env:JWT_SIGNING_KEY}
    JWT_TTL: ${env:JWT_TTL}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource:
        - "*"

functions:
  api:
    handler: ./src/index.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
    vpc:
      securityGroupIds:
        - sg-0fe96f314854bde70
      subnetIds:
        - subnet-0f9af9f93b661a6ad
        - subnet-0315b540cb1a0f6a0
        - subnet-0f877550548ce2fa1
